name: 二二不得四
author: Y
url: https://2x2isnot4.com/
meta:
  # keywords: 二二不得四, 2x2, Yang, blog
  # description: 二二不得四
  # apple-mobile-web-app-title: 二二不得四
icon: /favicon.png
# rss: https://2x2isnot4.com/atom.xml
css:
  - /css/style.css?v=1.0.1
scripts:

blog:
  templates:
    post: blog/post.html
    tag: blog/tag.html
    list: blog/index.html
  urls:
    post: /posts/{{post}}
    tag: /tag/{{tag}}
    list: /
  pagination:
    count: 10
    pattern: /page/{{page}}

plugins:
  # disqus: 2x2isnot4
  googleAnalytics: UA-48373896-3
