name: website
author: author
url: http://localhost:3000
meta:
  keywords: static website
  description: this is an awesome website
  apple-mobile-web-app-title: static website
icon: /favicon.png
rss: http://localhost:3000/atom.xml
css:
  - /css/style.css?v=1.0.0
scripts:

blog:
  templates:
    post: blog/post.html
    tag: blog/tag.html
    list: blog/index.html
  urls:
    post: /posts/{{post}}
    tag: /tag/{{tag}}
    list: /
  pagination:
    count: 10
    pattern: /page/{{page}}

plugins:
  disqus:
  googleAnalytics:
